# Generated by Django 5.0.4 on 2024-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cart_phone_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
